// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Appointment struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AppointmentDate time.Time
	AppointmentTime time.Time
	PatientID       int32
	Reasoning       sql.NullString
}

type Chart struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	PatientID    int32
	Note         pqtype.NullRawMessage
	SignedStatus sql.NullBool
}

type Patient struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	LastName             string
	FirstName            string
	MiddleName           sql.NullString
	DateOfBirth          time.Time
	Sex                  string
	Gender               string
	SocialSecurityNumber sql.NullString
	Pharmacy             string
	Email                sql.NullString
	LocationAddress      string
	ZipCode              string
	CellPhoneNumber      sql.NullString
	HomePhoneNumber      sql.NullString
	MaritalStatus        sql.NullString
	PatientID            sql.NullInt32
	Insurance            sql.NullString
	PrimaryCareDoctor    sql.NullString
	ExtraNote            sql.NullString
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	HashedPassword string
	LastName       string
	FirstName      string
	Permissions    string
}
