// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username, hashed_password, 
    last_name, first_name, 
    permissions
)
VALUES(
    $1, $2, 
    $3, $4, 
    $5
)
`

type CreateUserParams struct {
	Username       string
	HashedPassword string
	LastName       string
	FirstName      string
	Permissions    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.LastName,
		arg.FirstName,
		arg.Permissions,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, username)
	return err
}

const getHashedPassword = `-- name: GetHashedPassword :one
SELECT hashed_password, permissions
FROM users
WHERE username = $1
`

type GetHashedPasswordRow struct {
	HashedPassword string
	Permissions    string
}

func (q *Queries) GetHashedPassword(ctx context.Context, username string) (GetHashedPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, getHashedPassword, username)
	var i GetHashedPasswordRow
	err := row.Scan(&i.HashedPassword, &i.Permissions)
	return i, err
}

const updateUserInfo = `-- name: UpdateUserInfo :exec
UPDATE users
SET hashed_password = $2, last_name = $3, first_name = $4
WHERE username = $1
`

type UpdateUserInfoParams struct {
	Username       string
	HashedPassword string
	LastName       string
	FirstName      string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfo,
		arg.Username,
		arg.HashedPassword,
		arg.LastName,
		arg.FirstName,
	)
	return err
}

const updateUserPermissions = `-- name: UpdateUserPermissions :exec
UPDATE users
SET permissions = $2, updated_at = NOW()
WHERE username = $1
`

type UpdateUserPermissionsParams struct {
	Username    string
	Permissions string
}

func (q *Queries) UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPermissions, arg.Username, arg.Permissions)
	return err
}
