// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AppointmentDate time.Time
	ChartID         int32
	Reasoning       sql.NullString
}

type Patient struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	LastName             string
	FirstName            string
	MiddleName           sql.NullString
	DateOfBirth          time.Time
	Sex                  string
	SocialSecurityNumber sql.NullString
	Pharmacy             sql.NullString
	Email                sql.NullString
	LocationAddress      string
	ZipCode              string
	CellPhoneNumber      sql.NullString
	HomePhoneNumber      sql.NullString
	MaritalStatus        sql.NullString
	ChartID              sql.NullInt32
	PrimaryCareDoctor    sql.NullString
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	HashedPassword string
	LastName       string
	FirstName      string
	Permissions    string
}
