// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/chichigami/EMR/internal/models"

func (p *models.Patient) validateForm() map[string]string {
	errors := make(map[string]string)
	if len(p.LastName) == 0 {
		errors["lname"] = "Please Fill in patient's last name"
	}
	if len(p.FirstName) == 0 {
		errors["fname"] = "Please fill in patient's first name"
	}
	if len(p.DateOfBirth) == 0 {
		errors["DoB"] = "Please fill in a date of birth"
	}
	if len(p.Sex) == 0 {
		errors["sex"] = "Please fill in sex"
	}
	if p.Sex == "Other" || p.Sex == "O" {
		errors["extranotes"] = "Please ask patient what organs they have"
	}
	if len(p.Gender) == 0 {
		errors["geneder"] = "Please fill in gender"
	}
	if len(p.LocationAddress) == 0 {
		errors["address"] = "Please fill in address"
	}
	if len(p.ZipCode) == 0 {
		errors["zipcode"] = "Please fill in zip code"
	}
	if len(p.CellPhoneNumber) == 0 && len(p.HomePhoneNumber) == 0 {
		errors["phonenumber"] = "Please fill in one phone number"
	}
	return errors
}

func createPatientForm(values models.Patient, errors map[string]string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/patients/create\" class=\"\" id=\"createPatientForm\" hx-encoding=\"json\"></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

// <button hx-delete="/patients/id" hx-confirm="Are you sure you wish to delete this patient's chart?">
//
//	Delete
//
// </button>
var _ = templruntime.GeneratedTemplate
